package ec.gob.sri.celcer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2015-02-16T20:42:46.945-05:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://ec.gob.sri.ws.autorizacion", name = "AutorizacionComprobantes")
@XmlSeeAlso({ObjectFactory.class})
public interface AutorizacionComprobantes {

    @WebMethod
    @RequestWrapper(localName = "autorizacionComprobante", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "ec.gob.sri.celcer.AutorizacionComprobante")
    @ResponseWrapper(localName = "autorizacionComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "ec.gob.sri.celcer.AutorizacionComprobanteResponse")
    @WebResult(name = "RespuestaAutorizacionComprobante", targetNamespace = "")
    public ec.gob.sri.celcer.RespuestaComprobante autorizacionComprobante(
        @WebParam(name = "claveAccesoComprobante", targetNamespace = "")
        java.lang.String claveAccesoComprobante
    );

    @WebMethod
    @RequestWrapper(localName = "autorizacionComprobanteLote", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "ec.gob.sri.celcer.AutorizacionComprobanteLote")
    @ResponseWrapper(localName = "autorizacionComprobanteLoteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "ec.gob.sri.celcer.AutorizacionComprobanteLoteResponse")
    @WebResult(name = "RespuestaAutorizacionLote", targetNamespace = "")
    public ec.gob.sri.celcer.RespuestaLote autorizacionComprobanteLote(
        @WebParam(name = "claveAccesoLote", targetNamespace = "")
        java.lang.String claveAccesoLote
    );
}
